apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ghcr-aostrom-dev
  namespace: test-app
spec:
  image: ghcr.io/aostrom-dev/app
  provider: generic
  secretRef: ghcr-credentials
  interval: 1m
