apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: test-app-nightly
  namespace: test-app
spec:
  imageRepositoryRef:
    name: ghcr-aostrom-dev
  filterTags:
    pattern: "^nightly-(?P<date>[0-9]+)-(?P<time>[0-9]+)-([a-zA-Z0-9]*)"
    extract: "$date$time"
  policy:
    numerical:
      order: asc
