apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour-release
  namespace: contour
spec:
  interval: 30m
  chart:
    spec:
      chart: contour
      version: "18.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: contour
      interval: 12h
  values:
